# Generated by Django 4.2.13 on 2026-07-30 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def fix_duplicate_stage_Products(apps, schema_editor):
    """Merge the duplicate Products stage into stage 5."""
    Company = apps.get_model('helloworld', 'Company')
    Stage = apps.get_model('helloworld', 'Stage')

    try:
        correct_stage = Stage.objects.get(id=5)
        duplicate_stage = Stage.objects.get(id=6)

        companies = Company.objects.filter(Stage=duplicate_stage)
        for company in companies:
            company.Stage.remove(duplicate_stage)
            company.Stage.add(correct_stage)

        duplicate_stage.delete()
    except Stage.DoesNotExist:
        pass


def fix_duplicate_stage_Markets(apps, schema_editor):
    """Merge duplicate Markets stages into stage 7."""
    Company = apps.get_model('helloworld', 'Company')
    Stage = apps.get_model('helloworld', 'Stage')

    try:
        correct_stage = Stage.objects.get(id=7)
        duplicate_stages = [
            Stage.objects.get(id=8),
            Stage.objects.get(id=9),
            Stage.objects.get(id=10),
        ]

        for duplicate_stage in duplicate_stages:
            companies = Company.objects.filter(Stage=duplicate_stage)
            for company in companies:
                company.Stage.remove(duplicate_stage)
                company.Stage.add(correct_stage)

            duplicate_stage.delete()
    except Stage.DoesNotExist:
        pass

class Migration(migrations.Migration):

    replaces = [('helloworld', '0001_initial'), ('helloworld', '0002_auto_20240510_0621'), ('helloworld', '0003_auto_20240511_2246'), ('helloworld', '0004_resources'), ('helloworld', '0005_alter_resources_image'), ('helloworld', '0006_alter_resources_title'), ('helloworld', '0007_auto_20240521_1855'), ('helloworld', '0008_alter_resources_image'), ('helloworld', '0009_uploadindex'), ('helloworld', '0010_alter_category_options_alter_company_options_and_more'), ('helloworld', '0011_company_latitude_company_longitude_and_more'), ('helloworld', '0012_remove_pendingchanges_companyid_and_more'), ('helloworld', '0013_resources_priority'), ('helloworld', '0014_company_datecreated_company_lastupdated_and_more'), ('helloworld', '0015_remove_stage_category_and_resolve_duplicates'), ('helloworld', '0016_alter_company_datecreated_and_more'), ('helloworld', '0017_pendingchanges_status')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'Categories',
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Grower',
                'verbose_name': 'Grower',
                'verbose_name_plural': 'Growers',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Industry',
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productGroup', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'ProductGroup',
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'Solutions',
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=1024)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'Stage',
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='stakeholderGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholderGroup', models.CharField(max_length=1024)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'Groups',
                'verbose_name': 'Stakeholder Group',
                'verbose_name_plural': 'Stakeholder Groups',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Status',
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='PendingChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.CharField(max_length=250)),
                ('changeType', models.CharField(max_length=250)),
                ('editId', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'PendingChanges',
                'verbose_name': 'Pending Change',
                'verbose_name_plural': 'Pending Changes',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('image', models.CharField(blank=True, max_length=1024)),
                ('text', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'db_table': 'Resources',
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='UploadIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingID', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'UploadIndex',
                'verbose_name': 'Upload Index',
                'verbose_name_plural': 'Upload Indexes',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcKey', models.CharField(blank=True, default=None, max_length=128)),
                ('Name', models.CharField(max_length=250)),
                ('Headquarters', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, default=None, max_length=512)),
                ('Sales', models.CharField(blank=True, max_length=255)),
                ('Product', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(blank=True, max_length=250)),
                ('State', models.CharField(blank=True, max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('Website', models.CharField(blank=True, max_length=512)),
                ('Products', models.CharField(blank=True, max_length=250)),
                ('sasContact', models.CharField(blank=True, max_length=250)),
                ('Description', models.CharField(blank=True, max_length=2048)),
                ('pubPriv', models.CharField(blank=True, max_length=128)),
                ('Ticker', models.CharField(blank=True, max_length=128)),
                ('Naics', models.CharField(blank=True, max_length=250)),
                ('Phone', models.CharField(blank=True, max_length=250)),
                ('Email', models.CharField(blank=True, max_length=250)),
                ('Stakeholder', models.CharField(blank=True, max_length=250)),
                ('Principal', models.CharField(blank=True, max_length=250)),
                ('Founded', models.CharField(blank=True, max_length=250)),
                ('Employees', models.CharField(blank=True, max_length=250)),
                ('parentCompany', models.CharField(blank=True, max_length=250)),
                ('onMarket', models.CharField(blank=True, max_length=250)),
                ('productName', models.CharField(blank=True, max_length=250)),
                ('SKU', models.CharField(blank=True, max_length=250)),
                ('Notes', models.CharField(blank=True, max_length=1024)),
                ('processingFocus', models.CharField(blank=True, max_length=1024)),
                ('facilitySize', models.CharField(blank=True, max_length=250)),
                ('biomassCap', models.CharField(blank=True, max_length=250)),
                ('extractionType', models.CharField(blank=True, max_length=1024)),
                ('GMP', models.CharField(blank=True, max_length=250)),
                ('news', models.CharField(blank=True, max_length=1024)),
                ('reviews', models.CharField(blank=True, max_length=512)),
                ('Category', models.ManyToManyField(blank=True, to='helloworld.category')),
                ('Grower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.grower')),
                ('Industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.industry')),
                ('Solutions', models.ManyToManyField(blank=True, to='helloworld.solution')),
                ('Stage', models.ManyToManyField(blank=True, to='helloworld.stage')),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.status')),
                ('productGroup', models.ManyToManyField(blank=True, to='helloworld.productgroup')),
                ('stakeholderGroup', models.ManyToManyField(blank=True, to='helloworld.stakeholdergroups')),
            ],
            options={
                'db_table': 'Companies',
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='PendingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcKey', models.CharField(blank=True, default=None, max_length=128)),
                ('Name', models.CharField(max_length=250)),
                ('Headquarters', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, default=None, max_length=512)),
                ('Sales', models.CharField(blank=True, max_length=255)),
                ('Product', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(blank=True, max_length=250)),
                ('State', models.CharField(blank=True, max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('Website', models.CharField(blank=True, max_length=512)),
                ('Products', models.CharField(blank=True, max_length=250)),
                ('sasContact', models.CharField(blank=True, max_length=250)),
                ('Description', models.CharField(blank=True, max_length=2048)),
                ('pubPriv', models.CharField(blank=True, max_length=128)),
                ('Ticker', models.CharField(blank=True, max_length=128)),
                ('Naics', models.CharField(blank=True, max_length=250)),
                ('Phone', models.CharField(blank=True, max_length=250)),
                ('Email', models.CharField(blank=True, max_length=250)),
                ('Stakeholder', models.CharField(blank=True, max_length=250)),
                ('Principal', models.CharField(blank=True, max_length=250)),
                ('Founded', models.CharField(blank=True, max_length=250)),
                ('Employees', models.CharField(blank=True, max_length=250)),
                ('parentCompany', models.CharField(blank=True, max_length=250)),
                ('onMarket', models.CharField(blank=True, max_length=250)),
                ('productName', models.CharField(blank=True, max_length=250)),
                ('SKU', models.CharField(blank=True, max_length=250)),
                ('Notes', models.CharField(blank=True, max_length=1024)),
                ('processingFocus', models.CharField(blank=True, max_length=1024)),
                ('facilitySize', models.CharField(blank=True, max_length=250)),
                ('biomassCap', models.CharField(blank=True, max_length=250)),
                ('extractionType', models.CharField(blank=True, max_length=1024)),
                ('GMP', models.CharField(blank=True, max_length=250)),
                ('news', models.CharField(blank=True, max_length=1024)),
                ('reviews', models.CharField(blank=True, max_length=512)),
                ('Category', models.ManyToManyField(blank=True, to='helloworld.category')),
                ('Grower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.grower')),
                ('Industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.industry')),
                ('Solutions', models.ManyToManyField(blank=True, to='helloworld.solution')),
                ('Stage', models.ManyToManyField(blank=True, to='helloworld.stage')),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.status')),
                ('productGroup', models.ManyToManyField(blank=True, to='helloworld.productgroup')),
                ('stakeholderGroup', models.ManyToManyField(blank=True, to='helloworld.stakeholdergroups')),
            ],
            options={
                'db_table': 'PendingCompanies',
                'verbose_name': 'Pending Company',
                'verbose_name_plural': 'Pending Companies',
            },
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='grower',
            table='grower',
        ),
        migrations.AlterModelTable(
            name='industry',
            table='industry',
        ),
        migrations.AlterModelTable(
            name='pendingchanges',
            table='pending_change',
        ),
        migrations.AlterModelTable(
            name='pendingcompany',
            table='pending_company',
        ),
        migrations.AlterModelTable(
            name='productgroup',
            table='product_group',
        ),
        migrations.AlterModelTable(
            name='resources',
            table='resource',
        ),
        migrations.AlterModelTable(
            name='solution',
            table='solution',
        ),
        migrations.AlterModelTable(
            name='stage',
            table='stage',
        ),
        migrations.AlterModelTable(
            name='stakeholdergroups',
            table='stakeholder_group',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
        migrations.AlterModelTable(
            name='uploadindex',
            table='upload_index',
        ),
        migrations.AddField(
            model_name='company',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pendingcompany',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pendingcompany',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.RemoveField(
            model_name='pendingchanges',
            name='companyId',
        ),
        migrations.RemoveField(
            model_name='pendingchanges',
            name='editId',
        ),
        migrations.AddField(
            model_name='company',
            name='pendingChanges',
            field=models.ManyToManyField(through='helloworld.PendingChanges', to='helloworld.pendingcompany'),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.company'),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='pending_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.pendingcompany'),
        ),
        migrations.AddField(
            model_name='resources',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 8, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pendingcompany',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 8, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingcompany',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(fix_duplicate_stage_Products),
        migrations.RunPython(fix_duplicate_stage_Markets),
        migrations.RemoveField(
            model_name='stage',
            name='category',
        ),
        migrations.AlterField(
            model_name='company',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=250),
        ),
    ]
